class CityData {
  static const List<Map<String, String>> cities = [
    {'name': 'Abohar', 'url': 'https://housing.com/in/buy/real-estate-abohar'},
    {'name': 'Abu Dhabi', 'url': 'https://housing.com/in/buy/real-estate-abu_dhabi'},
    {'name': 'Adilabad', 'url': 'https://housing.com/in/buy/real-estate-adilabad'},
    {'name': 'Agarmalwa', 'url': 'https://housing.com/in/buy/real-estate-agarmalwa'},
    {'name': 'Agartala', 'url': 'https://housing.com/in/buy/real-estate-agartala'},
    {'name': 'Agra', 'url': 'https://housing.com/in/buy/real-estate-agra_uttar_pradesh'},
    {'name': 'Ahmedabad', 'url': 'https://housing.com/buy-real-estate-ahmedabad'},
    {'name': 'Ahmednagar', 'url': 'https://housing.com/in/buy/real-estate-ahmednagar'},
    {'name': 'Aizawl', 'url': 'https://housing.com/in/buy/real-estate-aizawl'},
    {'name': 'Ajman', 'url': 'https://housing.com/in/buy/real-estate-ajman'},
    {'name': 'Ajmer', 'url': 'https://housing.com/in/buy/real-estate-ajmer'},
    {'name': 'Akola', 'url': 'https://housing.com/in/buy/real-estate-akola'},
    {'name': 'Alappuzha', 'url': 'https://housing.com/in/buy/real-estate-alappuzha'},
    {'name': 'Alibag', 'url': 'https://housing.com/in/buy/real-estate-alibag'},
    {'name': 'Aligarh', 'url': 'https://housing.com/in/buy/real-estate-aligarh'},
    {'name': 'Alipurduar', 'url': 'https://housing.com/in/buy/real-estate-alipurduar'},
    {'name': 'Alirajpur', 'url': 'https://housing.com/in/buy/real-estate-alirajpur'},
    {'name': 'Allahabad', 'url': 'https://housing.com/in/buy/real-estate-allahabad'},
    {'name': 'Almora', 'url': 'https://housing.com/in/buy/real-estate-almora_1'},
    {'name': 'Aluva', 'url': 'https://housing.com/in/buy/real-estate-aluva'},
    {'name': 'Alwar', 'url': 'https://housing.com/in/buy/real-estate-alwar_rajasthan'},
    {'name': 'Ambala', 'url': 'https://housing.com/in/buy/real-estate-ambala'},
    {'name': 'Ambedkar Nagar', 'url': 'https://housing.com/in/buy/real-estate-ambedkar_nagar'},
    {'name': 'Amethi', 'url': 'https://housing.com/in/buy/real-estate-amethi'},
    {'name': 'Amravati', 'url': 'https://housing.com/in/buy/real-estate-amravati'},
    {'name': 'Amreli', 'url': 'https://housing.com/in/buy/real-estate-amreli_gujarat'},
    {'name': 'Amritsar', 'url': 'https://housing.com/in/buy/real-estate-amritsar'},
    {'name': 'Amroha', 'url': 'https://housing.com/in/buy/real-estate-amroha'},
    {'name': 'Anand', 'url': 'https://housing.com/in/buy/real-estate-anand'},
    {'name': 'Anantapur', 'url': 'https://housing.com/in/buy/real-estate-anantapur_andhra_pradesh'},
    {'name': 'Anantnag', 'url': 'https://housing.com/in/buy/real-estate-anantnag'},
    {'name': 'Angul', 'url': 'https://housing.com/in/buy/real-estate-angul'},
    {'name': 'Anjaw', 'url': 'https://housing.com/in/buy/real-estate-anjaw'},
    {'name': 'Ankleshwar', 'url': 'https://housing.com/in/buy/real-estate-ankleshwar'},
    {'name': 'Anuppur', 'url': 'https://housing.com/in/buy/real-estate-anuppur_madhya_pradesh'},
    {'name': 'Araria', 'url': 'https://housing.com/in/buy/real-estate-araria'},
    {'name': 'Aravalli', 'url': 'https://housing.com/in/buy/real-estate-aravalli'},
    {'name': 'Ariyalur', 'url': 'https://housing.com/in/buy/real-estate-ariyalur'},
    {'name': 'Arrah', 'url': 'https://housing.com/in/buy/real-estate-arrah'},
    {'name': 'Arwal', 'url': 'https://housing.com/in/buy/real-estate-arwal'},
    {'name': 'Asansol', 'url': 'https://housing.com/in/buy/real-estate-asansol'},
    {'name': 'Ashoknagar', 'url': 'https://housing.com/in/buy/real-estate-ashoknagar'},
    {'name': 'Auraiya', 'url': 'https://housing.com/in/buy/real-estate-auraiya'},
    {'name': 'Aurangabad', 'url': 'https://housing.com/in/buy/real-estate-aurangabad_maharashtra'},
    {'name': 'Aurangabad, Bihar', 'url': 'https://housing.com/in/buy/real-estate-aurangabad_bihar'},
    {'name': 'Ayodhya', 'url': 'https://housing.com/in/buy/real-estate-ayodhya_1'},
    {'name': 'Azamgarh', 'url': 'https://housing.com/in/buy/real-estate-azamgarh'},
    {'name': 'Baddi', 'url': 'https://housing.com/in/buy/real-estate-baddi'},
    {'name': 'Badgam', 'url': 'https://housing.com/in/buy/real-estate-badgam'},
    {'name': 'Bagalkot', 'url': 'https://housing.com/in/buy/real-estate-bagalkot'},
    {'name': 'Bageshwar', 'url': 'https://housing.com/in/buy/real-estate-bageshwar'},
    {'name': 'Baghpat', 'url': 'https://housing.com/in/buy/real-estate-baghpat'},
    {'name': 'Bahadurgarh', 'url': 'https://housing.com/in/buy/real-estate-bahadurgarh'},
    {'name': 'Bahraich', 'url': 'https://housing.com/in/buy/real-estate-bahraich'},
    {'name': 'Baksa', 'url': 'https://housing.com/in/buy/real-estate-baksa'},
    {'name': 'Balaghat', 'url': 'https://housing.com/in/buy/real-estate-balaghat'},
    {'name': 'Balangir', 'url': 'https://housing.com/in/buy/real-estate-balangir'},
    {'name': 'Balasore', 'url': 'https://housing.com/in/buy/real-estate-balasore'},
    {'name': 'Ballia', 'url': 'https://housing.com/in/buy/real-estate-ballia'},
    {'name': 'Balod', 'url': 'https://housing.com/in/buy/real-estate-balod'},
    {'name': 'Balrampur', 'url': 'https://housing.com/in/buy/real-estate-balrampur'},
    {'name': 'Banaskantha', 'url': 'https://housing.com/in/buy/real-estate-banaskantha'},
    {'name': 'Banda', 'url': 'https://housing.com/in/buy/real-estate-banda'},
    {'name': 'Bandipora', 'url': 'https://housing.com/in/buy/real-estate-bandipora'},
    {'name': 'Banka', 'url': 'https://housing.com/in/buy/real-estate-banka'},
    {'name': 'Bankura', 'url': 'https://housing.com/in/buy/real-estate-bankura'},
    {'name': 'Banswara', 'url': 'https://housing.com/in/buy/real-estate-banswara'},
    {'name': 'Barabanki', 'url': 'https://housing.com/in/buy/real-estate-barabanki'},
    {'name': 'Baramulla', 'url': 'https://housing.com/in/buy/real-estate-baramulla'},
    {'name': 'Baran', 'url': 'https://housing.com/in/buy/real-estate-baran'},
    {'name': 'Bardhaman', 'url': 'https://housing.com/in/buy/real-estate-burdwan'},
    {'name': 'Bareilly', 'url': 'https://housing.com/in/buy/real-estate-bareilly_uttar_pradesh'},
    {'name': 'Bargarh', 'url': 'https://housing.com/in/buy/real-estate-bargarh'},
    {'name': 'Barmer', 'url': 'https://housing.com/in/buy/real-estate-barmer_rajasthan'},
    {'name': 'Barnala', 'url': 'https://housing.com/in/buy/real-estate-barnala_1'},
    {'name': 'Barpeta', 'url': 'https://housing.com/in/buy/real-estate-barpeta'},
    {'name': 'Barwani', 'url': 'https://housing.com/in/buy/real-estate-barwani'},
    {'name': 'Bastar', 'url': 'https://housing.com/in/buy/real-estate-bastar'},
    {'name': 'Basti', 'url': 'https://housing.com/in/buy/real-estate-basti'},
    {'name': 'Bathinda', 'url': 'https://housing.com/in/buy/real-estate-bathinda_punjab'},
    {'name': 'Bauda', 'url': 'https://housing.com/in/buy/real-estate-bauda'},
    {'name': 'Beawar', 'url': 'https://housing.com/in/buy/real-estate-beawar'},
    {'name': 'Beed', 'url': 'https://housing.com/in/buy/real-estate-beed'},
    {'name': 'Begusarai', 'url': 'https://housing.com/in/buy/real-estate-begusarai'},
    {'name': 'Belagavi', 'url': 'https://housing.com/in/buy/real-estate-belgaum'},
    {'name': 'Bellary', 'url': 'https://housing.com/in/buy/real-estate-bellary'},
    {'name': 'Bemetara', 'url': 'https://housing.com/in/buy/real-estate-bemetara'},
    {'name': 'Bengaluru', 'url': 'https://housing.com/in/buy/real-estate-bangalore'},
    {'name': 'Berhampore', 'url': 'https://housing.com/in/buy/real-estate-berhampore'},
    {'name': 'Bettiah', 'url': 'https://housing.com/in/buy/real-estate-bettiah'},
    {'name': 'Betul', 'url': 'https://housing.com/in/buy/real-estate-betul'},
    {'name': 'Bhadohi', 'url': 'https://housing.com/in/buy/real-estate-bhadohi'},
    {'name': 'Bhadrak', 'url': 'https://housing.com/in/buy/real-estate-bhadrak'},
    {'name': 'Bhagalpur', 'url': 'https://housing.com/in/buy/real-estate-bhagalpur'},
    {'name': 'Bhandara', 'url': 'https://housing.com/in/buy/real-estate-bhandara'},
    {'name': 'Bharatpur', 'url': 'https://housing.com/in/buy/real-estate-bharatpur'},
    {'name': 'Bharuch', 'url': 'https://housing.com/in/buy/real-estate-bharuch_india'},
    {'name': 'Bhatapara', 'url': 'https://housing.com/in/buy/real-estate-bhatapara'},
    {'name': 'Bhavnagar', 'url': 'https://housing.com/in/buy/real-estate-bhavnagar_1'},
    {'name': 'Bhilai', 'url': 'https://housing.com/in/buy/real-estate-bhilai'},
    {'name': 'Bhilwara', 'url': 'https://housing.com/in/buy/real-estate-bhilwara'},
    {'name': 'Bhimavaram', 'url': 'https://housing.com/in/buy/real-estate-bhimavaram'},
    {'name': 'Bhind', 'url': 'https://housing.com/in/buy/real-estate-bhind'},
    {'name': 'Bhiwadi', 'url': 'https://housing.com/in/buy/real-estate-bhiwadi'},
    {'name': 'Bhiwani', 'url': 'https://housing.com/in/buy/real-estate-bhiwani'},
    {'name': 'Bhojpur', 'url': 'https://housing.com/in/buy/real-estate-bhojpur'},
    {'name': 'Bhopal', 'url': 'https://housing.com/buy-real-estate-bhopal'},
    {'name': 'Bhubaneswar', 'url': 'https://housing.com/in/buy/real-estate-bhubaneswar'},
    {'name': 'Bhuj', 'url': 'https://housing.com/in/buy/real-estate-bhuj'},
    {'name': 'Bidar', 'url': 'https://housing.com/in/buy/real-estate-bidar'},
    {'name': 'Bihar Sharif', 'url': 'https://housing.com/in/buy/real-estate-bihar_sharif'},
    {'name': 'Bijapur', 'url': 'https://housing.com/in/buy/real-estate-bijapur'},
    {'name': 'Bijnor', 'url': 'https://housing.com/in/buy/real-estate-bijnor'},
    {'name': 'Bikaner', 'url': 'https://housing.com/in/buy/real-estate-bikaner'},
    {'name': 'Bilaspur', 'url': 'https://housing.com/in/buy/real-estate-bilaspur'},
    {'name': 'Bilaspur, HP', 'url': 'https://housing.com/in/buy/real-estate-bilaspur_hp'},
    {'name': 'Bilimora', 'url': 'https://housing.com/in/buy/real-estate-bilimora'},
    {'name': 'Birbhum', 'url': 'https://housing.com/in/buy/real-estate-birbhum'},
    {'name': 'Bishnupur', 'url': 'https://housing.com/in/buy/real-estate-bishnupur'},
    {'name': 'Bokaro', 'url': 'https://housing.com/in/buy/real-estate-bokaro_1'},
    {'name': 'Bolpur-Santiniketan', 'url': 'https://housing.com/in/buy/real-estate-bolpur'},
    {'name': 'Bongaigaon', 'url': 'https://housing.com/in/buy/real-estate-bongaigaon'},
    {'name': 'Botad', 'url': 'https://housing.com/in/buy/real-estate-botad'},
    {'name': 'Brajrajnagar', 'url': 'https://housing.com/in/buy/real-estate-brajrajnagar'},
    {'name': 'Budaun', 'url': 'https://housing.com/in/buy/real-estate-budaun'},
    {'name': 'Bulandshahr', 'url': 'https://housing.com/in/buy/real-estate-bulandshahr_uttar_pradesh'},
    {'name': 'Buldhana', 'url': 'https://housing.com/in/buy/real-estate-buldhana'},
    {'name': 'Bundi', 'url': 'https://housing.com/in/buy/real-estate-bundi'},
    {'name': 'Burhanpur', 'url': 'https://housing.com/in/buy/real-estate-burhanpur'},
    {'name': 'Buxar', 'url': 'https://housing.com/in/buy/real-estate-buxar'},
    {'name': 'Cachar', 'url': 'https://housing.com/in/buy/real-estate-cachar'},
    {'name': 'Chamarajanagar', 'url': 'https://housing.com/in/buy/real-estate-chamarajanagar'},
    {'name': 'Chamba', 'url': 'https://housing.com/in/buy/real-estate-chamba_district'},
    {'name': 'Chamoli', 'url': 'https://housing.com/in/buy/real-estate-chamoli'},
    {'name': 'Champawat', 'url': 'https://housing.com/in/buy/real-estate-champawat'},
    {'name': 'Champhai', 'url': 'https://housing.com/in/buy/real-estate-champhai'},
    {'name': 'Chandauli', 'url': 'https://housing.com/in/buy/real-estate-chandauli'},
    {'name': 'Chandel', 'url': 'https://housing.com/in/buy/real-estate-chandel'},
    {'name': 'Chandigarh', 'url': 'https://housing.com/in/buy/real-estate-chandigarh_india'},
    {'name': 'Chandrapur', 'url': 'https://housing.com/in/buy/real-estate-chandrapur'},
    {'name': 'Changlang', 'url': 'https://housing.com/in/buy/real-estate-changlang'},
    {'name': 'Charkhi Dadri', 'url': 'https://housing.com/in/buy/real-estate-charkhi_dadri'},
    {'name': 'Chatra', 'url': 'https://housing.com/in/buy/real-estate-chatra'},
    {'name': 'Chennai', 'url': 'https://housing.com/in/buy/real-estate-chennai'},
    {'name': 'Chhapra', 'url': 'https://housing.com/in/buy/real-estate-chhapra_1'},
    {'name': 'Chhatarpur', 'url': 'https://housing.com/in/buy/real-estate-chhatarpur'},
    {'name': 'Chhindwara', 'url': 'https://housing.com/in/buy/real-estate-chhindwara'},
    {'name': 'Chhota Udepur', 'url': 'https://housing.com/in/buy/real-estate-chhota_udepur'},
    {'name': 'Chikkamagaluru', 'url': 'https://housing.com/in/buy/real-estate-chickmagaluru'},
    {'name': 'Chiplun', 'url': 'https://housing.com/in/buy/real-estate-chiplun'},
    {'name': 'Chirang', 'url': 'https://housing.com/in/buy/real-estate-chirang'},
    {'name': 'Chitradurga', 'url': 'https://housing.com/in/buy/real-estate-chitradurga'},
    {'name': 'Chitrakoot', 'url': 'https://housing.com/in/buy/real-estate-chitrakoot'},
    {'name': 'Chittoor', 'url': 'https://housing.com/in/buy/real-estate-chittoor'},
    {'name': 'Chittorgarh', 'url': 'https://housing.com/in/buy/real-estate-chittorgarh'},
    {'name': 'Churachandpur', 'url': 'https://housing.com/in/buy/real-estate-churachandpur'},
    {'name': 'Churu', 'url': 'https://housing.com/in/buy/real-estate-churu'},
    {'name': 'Coimbatore', 'url': 'https://housing.com/buy-real-estate-coimbatore'},
    {'name': 'Cooch Behar', 'url': 'https://housing.com/in/buy/real-estate-cooch_behar'},
    {'name': 'Cuddalore', 'url': 'https://housing.com/in/buy/real-estate-cuddalore'},
    {'name': 'Cuttack', 'url': 'https://housing.com/in/buy/real-estate-cuttack'},
    {'name': 'Dadra And Nagar Haveli', 'url': 'https://housing.com/in/buy/real-estate-dadra_and_nagar_haveli'},
    {'name': 'Dahod', 'url': 'https://housing.com/in/buy/real-estate-dahod'},
    {'name': 'Dakshin Dinajpur', 'url': 'https://housing.com/in/buy/real-estate-dakshin_dinajpur'},
    {'name': 'Dakshina Kannada', 'url': 'https://housing.com/in/buy/real-estate-dakshina_kannada_1'},
    {'name': 'Daltonganj', 'url': 'https://housing.com/in/buy/real-estate-daltonganj'},
    {'name': 'Daman', 'url': 'https://housing.com/in/buy/real-estate-daman_gujarat'},
    {'name': 'Damoh', 'url': 'https://housing.com/in/buy/real-estate-damoh'},
    {'name': 'Dang', 'url': 'https://housing.com/in/buy/real-estate-dang'},
    {'name': 'Dantewada', 'url': 'https://housing.com/in/buy/real-estate-dantewada'},
    {'name': 'Dapoli', 'url': 'https://housing.com/in/buy/real-estate-dapoli'},
    {'name': 'Darbhanga', 'url': 'https://housing.com/in/buy/real-estate-darbhanga'},
    {'name': 'Darjeeling', 'url': 'https://housing.com/in/buy/real-estate-darjeeling'},
    {'name': 'Darrang', 'url': 'https://housing.com/in/buy/real-estate-darrang'},
    {'name': 'Datia', 'url': 'https://housing.com/in/buy/real-estate-datia'},
    {'name': 'Dausa', 'url': 'https://housing.com/in/buy/real-estate-dausa_rajasthan'},
    {'name': 'Davanagere', 'url': 'https://housing.com/in/buy/real-estate-davanagere'},
    {'name': 'Dehradun', 'url': 'https://housing.com/buy-real-estate-dehradun'},
    {'name': 'Dehri On Sone', 'url': 'https://housing.com/in/buy/real-estate-dehri_on_sone'},
    {'name': 'Delhi', 'url': 'https://housing.com/in/buy/real-estate-new_delhi'},
    {'name': 'Deogarh', 'url': 'https://housing.com/in/buy/real-estate-deogarh'},
    {'name': 'Deoghar', 'url': 'https://housing.com/in/buy/real-estate-deoghar'},
    {'name': 'Deoria', 'url': 'https://housing.com/in/buy/real-estate-deoria'},
    {'name': 'Dera Bassi', 'url': 'https://housing.com/in/buy/real-estate-dera_bassi'},
    {'name': 'Devbhoomi Dwarka', 'url': 'https://housing.com/in/buy/real-estate-dwarka_india'},
    {'name': 'Dewas', 'url': 'https://housing.com/in/buy/real-estate-dewas'},
    {'name': 'Dhalai', 'url': 'https://housing.com/in/buy/real-estate-dhalai'},
    {'name': 'Dhamtari', 'url': 'https://housing.com/in/buy/real-estate-dhamtari'},
    {'name': 'Dhanbad', 'url': 'https://housing.com/in/buy/real-estate-dhanbad'},
    {'name': 'Dhar', 'url': 'https://housing.com/in/buy/real-estate-dhar'},
    {'name': 'Dharamsala', 'url': 'https://housing.com/in/buy/real-estate-dharamsala'},
    {'name': 'Dharmapuri', 'url': 'https://housing.com/in/buy/real-estate-dharmapuri'},
    {'name': 'Dharuhera', 'url': 'https://housing.com/in/buy/real-estate-dharuhera'},
    {'name': 'Dhemaji', 'url': 'https://housing.com/in/buy/real-estate-dhemaji'},
    {'name': 'Dhenkanal', 'url': 'https://housing.com/in/buy/real-estate-dhenkanal'},
    {'name': 'Dholera', 'url': 'https://housing.com/in/buy/real-estate-dholera'},
    {'name': 'Dholka', 'url': 'https://housing.com/in/buy/real-estate-dholka'},
    {'name': 'Dholpur', 'url': 'https://housing.com/in/buy/real-estate-dholpur'},
    {'name': 'Dhubri', 'url': 'https://housing.com/in/buy/real-estate-dhubri'},
    {'name': 'Dhule', 'url': 'https://housing.com/in/buy/real-estate-dhule'},
    {'name': 'Dibang Valley', 'url': 'https://housing.com/in/buy/real-estate-dibang_valley'},
    {'name': 'Dibrugarh', 'url': 'https://housing.com/in/buy/real-estate-dibrugarh'},
    {'name': 'Dima Hasao', 'url': 'https://housing.com/in/buy/real-estate-dima_hasao'},
    {'name': 'Dimapur', 'url': 'https://housing.com/in/buy/real-estate-dimapur'},
    {'name': 'Dindigul', 'url': 'https://housing.com/in/buy/real-estate-dindigul'},
    {'name': 'Dindori', 'url': 'https://housing.com/in/buy/real-estate-dindori'},
    {'name': 'Diu', 'url': 'https://housing.com/in/buy/real-estate-diu'},
    {'name': 'Doda', 'url': 'https://housing.com/in/buy/real-estate-doda'},
    {'name': 'Dubai', 'url': 'https://housing.com/in/buy/real-estate-a_dubaia_1'},
    {'name': 'Dumka', 'url': 'https://housing.com/in/buy/real-estate-dumka'},
    {'name': 'Dungarpur', 'url': 'https://housing.com/in/buy/real-estate-dungarpur'},
    {'name': 'Durg', 'url': 'https://housing.com/in/buy/real-estate-durg_chhattisgarh'},
    {'name': 'Durgapur', 'url': 'https://housing.com/in/buy/real-estate-durgapur_west_bengal_3'},
    {'name': 'East Garo Hills', 'url': 'https://housing.com/in/buy/real-estate-east_garo_hills_1'},
    {'name': 'East Godavari', 'url': 'https://housing.com/in/buy/real-estate-east_godavari'},
    {'name': 'East Jaintia Hills', 'url': 'https://housing.com/in/buy/real-estate-east_jaintia_hills'},
    {'name': 'East Kameng', 'url': 'https://housing.com/in/buy/real-estate-east_kameng'},
    {'name': 'East Khasi Hills', 'url': 'https://housing.com/in/buy/real-estate-east_khasi_hills'},
    {'name': 'East Siang', 'url': 'https://housing.com/in/buy/real-estate-east_siang_1'},
    {'name': 'East Sikkim', 'url': 'https://housing.com/in/buy/real-estate-east_sikkim'},
    {'name': 'East Singhbhum', 'url': 'https://housing.com/in/buy/real-estate-east_singhbhum'},
    {'name': 'Eluru', 'url': 'https://housing.com/in/buy/real-estate-eluru'},
    {'name': 'Ernakulam', 'url': 'https://housing.com/in/buy/real-estate-ernakulam'},
    {'name': 'Erode', 'url': 'https://housing.com/in/buy/real-estate-erode'},
    {'name': 'Etah', 'url': 'https://housing.com/in/buy/real-estate-etah'},
    {'name': 'Etawah', 'url': 'https://housing.com/in/buy/real-estate-etawah'},
    {'name': 'Faizabad', 'url': 'https://housing.com/in/buy/real-estate-faizabad'},
    {'name': 'Faridabad', 'url': 'https://housing.com/in/buy/real-estate-faridabad'},
    {'name': 'Faridkot', 'url': 'https://housing.com/in/buy/real-estate-faridkot'},
    {'name': 'Farrukhabad', 'url': 'https://housing.com/in/buy/real-estate-farrukhabad'},
    {'name': 'Fatehabad', 'url': 'https://housing.com/in/buy/real-estate-fatehabad'},
    {'name': 'Fatehgarh Sahib', 'url': 'https://housing.com/in/buy/real-estate-fatehgarh_sahib'},
    {'name': 'Fatehpur', 'url': 'https://housing.com/in/buy/real-estate-fatehpur'},
    {'name': 'Fazilka', 'url': 'https://housing.com/in/buy/real-estate-fazilka'},
    {'name': 'Firozabad', 'url': 'https://housing.com/in/buy/real-estate-firozabad'},
    {'name': 'Firozpur', 'url': 'https://housing.com/in/buy/real-estate-firozpur'},
    {'name': 'Gadag', 'url': 'https://housing.com/in/buy/real-estate-gadag'},
    {'name': 'Gadchiroli', 'url': 'https://housing.com/in/buy/real-estate-gadchiroli'},
    {'name': 'Gajapati', 'url': 'https://housing.com/in/buy/real-estate-gajapati'},
    {'name': 'Gajraula', 'url': 'https://housing.com/in/buy/real-estate-gajraula'},
    {'name': 'Ganderbal', 'url': 'https://housing.com/in/buy/real-estate-ganderbal'},
    {'name': 'Gandhinagar', 'url': 'https://housing.com/buy-real-estate-gandhinagar_gujarat'},
    {'name': 'Gangtok', 'url': 'https://housing.com/in/buy/real-estate-gangtok'},
    {'name': 'Ganjam', 'url': 'https://housing.com/in/buy/real-estate-ganjam'},
    {'name': 'Garhwa', 'url': 'https://housing.com/in/buy/real-estate-garhwa'},
    {'name': 'Gariaband', 'url': 'https://housing.com/in/buy/real-estate-gariaband'},
    {'name': 'Gaya', 'url': 'https://housing.com/in/buy/real-estate-gaya'},
    {'name': 'Ghaziabad', 'url': 'https://housing.com/in/buy/real-estate-ghaziabad'},
    {'name': 'Ghazipur', 'url': 'https://housing.com/in/buy/real-estate-ghazipur'},
    {'name': 'Gift City', 'url': 'https://housing.com/in/buy/real-estate-gift_city'},
    {'name': 'Gir Somnath', 'url': 'https://housing.com/in/buy/real-estate-gir_somnath'},
    {'name': 'Giridih', 'url': 'https://housing.com/in/buy/real-estate-giridih'},
    {'name': 'Goa', 'url': 'https://housing.com/in/buy/real-estate-goa'},
    {'name': 'Goalpara', 'url': 'https://housing.com/in/buy/real-estate-goalpara'},
    {'name': 'Godda', 'url': 'https://housing.com/in/buy/real-estate-godda'},
    {'name': 'Golaghat', 'url': 'https://housing.com/in/buy/real-estate-golaghat'},
    {'name': 'Gomati', 'url': 'https://housing.com/in/buy/real-estate-gomati'},
    {'name': 'Gonda', 'url': 'https://housing.com/in/buy/real-estate-gonda'},
    {'name': 'Gondal', 'url': 'https://housing.com/in/buy/real-estate-gondal'},
    {'name': 'Gondia', 'url': 'https://housing.com/in/buy/real-estate-gondia'},
    {'name': 'Gopalganj', 'url': 'https://housing.com/in/buy/real-estate-gopalganj'},
    {'name': 'Gorakhpur', 'url': 'https://housing.com/in/buy/real-estate-gorakhpur_1'},
    {'name': 'Greater Noida', 'url': 'https://housing.com/in/buy/real-estate-greater_noida'},
    {'name': 'Gudivada', 'url': 'https://housing.com/in/buy/real-estate-gudivada'},
    {'name': 'Gulbarga', 'url': 'https://housing.com/in/buy/real-estate-gulbarga_7'},
    {'name': 'Gumla', 'url': 'https://housing.com/in/buy/real-estate-gumla'},
    {'name': 'Guna', 'url': 'https://housing.com/in/buy/real-estate-guna'},
    {'name': 'Guntakal', 'url': 'https://housing.com/in/buy/real-estate-guntakal'},
    {'name': 'Guntur', 'url': 'https://housing.com/in/buy/real-estate-guntur_andhra_pradesh'},
    {'name': 'Gurdaspur', 'url': 'https://housing.com/in/buy/real-estate-gurdaspur'},
    {'name': 'Gurgaon', 'url': 'https://housing.com/in/buy/real-estate-gurgaon'},
    {'name': 'Guwahati', 'url': 'https://housing.com/buy-real-estate-guwahati'},
    {'name': 'Gwalior', 'url': 'https://housing.com/in/buy/real-estate-gwalior'},
    {'name': 'Hailakandi', 'url': 'https://housing.com/in/buy/real-estate-hailakandi'},
    {'name': 'Haldia', 'url': 'https://housing.com/in/buy/real-estate-haldia'},
    {'name': 'Hamirpur', 'url': 'https://housing.com/in/buy/real-estate-hamirpur'},
    {'name': 'Hanumangarh', 'url': 'https://housing.com/in/buy/real-estate-hanumangarh_1'},
    {'name': 'Hapur', 'url': 'https://housing.com/in/buy/real-estate-hapur'},
    {'name': 'Harda', 'url': 'https://housing.com/in/buy/real-estate-harda'},
    {'name': 'Hardoi', 'url': 'https://housing.com/in/buy/real-estate-hardoi'},
    {'name': 'Haridwar', 'url': 'https://housing.com/in/buy/real-estate-haridwar_uttarakhand'},
    {'name': 'Hassan', 'url': 'https://housing.com/in/buy/real-estate-hassan'},
    {'name': 'Hathras', 'url': 'https://housing.com/in/buy/real-estate-hathras'},
    {'name': 'Haveri', 'url': 'https://housing.com/in/buy/real-estate-haveri'},
    {'name': 'Hazaribagh', 'url': 'https://housing.com/in/buy/real-estate-hazaribagh'},
    {'name': 'Himatnagar', 'url': 'https://housing.com/in/buy/real-estate-himmatnagar'},
    {'name': 'Hindupur', 'url': 'https://housing.com/in/buy/real-estate-hindupur'},
    {'name': 'Hingoli', 'url': 'https://housing.com/in/buy/real-estate-hingoli'},
    {'name': 'Hisar', 'url': 'https://housing.com/in/buy/real-estate-hisar'},
    {'name': 'Hnahthial', 'url': 'https://housing.com/in/buy/real-estate-hnahthial'},
    {'name': 'Hodal', 'url': 'https://housing.com/in/buy/real-estate-hodal'},
    {'name': 'Hojai', 'url': 'https://housing.com/in/buy/real-estate-hojai'},
    {'name': 'Hoshangabad', 'url': 'https://housing.com/in/buy/real-estate-hoshangabad_1'},
    {'name': 'Hoshiarpur', 'url': 'https://housing.com/in/buy/real-estate-hoshiarpur'},
    {'name': 'Hospete', 'url': 'https://housing.com/in/buy/real-estate-hospet'},
    {'name': 'Hosur', 'url': 'https://housing.com/in/buy/real-estate-hosur'},
    {'name': 'Hubali-Dharwad', 'url': 'https://housing.com/in/buy/real-estate-dharwad'},
    {'name': 'Hyderabad', 'url': 'https://housing.com/in/buy/real-estate-hyderabad'},
    {'name': 'Idukki', 'url': 'https://housing.com/in/buy/real-estate-idukki'},
    {'name': 'Imphal', 'url': 'https://housing.com/in/buy/real-estate-imphal'},
    {'name': 'Indore', 'url': 'https://housing.com/buy-real-estate-indore'},
    {'name': 'Jabalpur', 'url': 'https://housing.com/buy-real-estate-jabalpur'},
    {'name': 'Jagadhri', 'url': 'https://housing.com/in/buy/real-estate-jagadhri'},
    {'name': 'Jagatsinghpur', 'url': 'https://housing.com/in/buy/real-estate-jagatsinghpur'},
    {'name': 'Jagdalpur', 'url': 'https://housing.com/in/buy/real-estate-jagdalpur_1'},
    {'name': 'Jagraon', 'url': 'https://housing.com/in/buy/real-estate-jagraon'},
    {'name': 'Jagtial', 'url': 'https://housing.com/in/buy/real-estate-jagtial'},
    {'name': 'Jaipur', 'url': 'https://housing.com/buy-real-estate-jaipur_rajasthan'},
    {'name': 'Jaisalmer', 'url': 'https://housing.com/in/buy/real-estate-jaisalmer'},
    {'name': 'Jajpur', 'url': 'https://housing.com/in/buy/real-estate-jajpur'},
    {'name': 'Jalandhar', 'url': 'https://housing.com/in/buy/real-estate-jalandhar_punjab'},
    {'name': 'Jalaun', 'url': 'https://housing.com/in/buy/real-estate-jalaun'},
    {'name': 'Jalgaon', 'url': 'https://housing.com/in/buy/real-estate-jalgaon'},
    {'name': 'Jalna', 'url': 'https://housing.com/in/buy/real-estate-jalna'},
    {'name': 'Jalore', 'url': 'https://housing.com/in/buy/real-estate-jalore'},
    {'name': 'Jalpaiguri', 'url': 'https://housing.com/in/buy/real-estate-jalpaiguri'},
    {'name': 'Jammu', 'url': 'https://housing.com/in/buy/real-estate-jammu'},
    {'name': 'Jamnagar', 'url': 'https://housing.com/in/buy/real-estate-jamnagar_1'},
    {'name': 'Jamshedpur', 'url': 'https://housing.com/buy-real-estate-jamshedpur'},
    {'name': 'Jamtara', 'url': 'https://housing.com/in/buy/real-estate-jamtara'},
    {'name': 'Jamui', 'url': 'https://housing.com/in/buy/real-estate-jamui'},
    {'name': 'Jangaon', 'url': 'https://housing.com/in/buy/real-estate-jangaon'},
    {'name': 'Janjgir-Champa', 'url': 'https://housing.com/in/buy/real-estate-janjgir_champa'},
    {'name': 'Jashpur', 'url': 'https://housing.com/in/buy/real-estate-jashpur'},
    {'name': 'Jaunpur', 'url': 'https://housing.com/in/buy/real-estate-jaunpur_1'},
    {'name': 'Jayashankar Bhupalpally', 'url': 'https://housing.com/in/buy/real-estate-bhupalpally'},
    {'name': 'Jehanabad', 'url': 'https://housing.com/in/buy/real-estate-jehanabad'},
    {'name': 'Jhabua', 'url': 'https://housing.com/in/buy/real-estate-jhabua'},
    {'name': 'Jhajjar', 'url': 'https://housing.com/in/buy/real-estate-jhajjar'},
    {'name': 'Jhalawar', 'url': 'https://housing.com/in/buy/real-estate-jhalawar'},
    {'name': 'Jhansi', 'url': 'https://housing.com/in/buy/real-estate-jhansi_uttar_pradesh'},
    {'name': 'Jharsuguda', 'url': 'https://housing.com/in/buy/real-estate-jharsuguda'},
    {'name': 'Jhunjhunu', 'url': 'https://housing.com/in/buy/real-estate-jhunjhunu'},
    {'name': 'Jind', 'url': 'https://housing.com/in/buy/real-estate-jind'},
    {'name': 'Jiribam', 'url': 'https://housing.com/in/buy/real-estate-jiribam'},
    {'name': 'Jodhpur', 'url': 'https://housing.com/in/buy/real-estate-jodhpur_rajasthan'},
    {'name': 'Jogulamba Gadwal', 'url': 'https://housing.com/in/buy/real-estate-jogulamba_gadwal'},
    {'name': 'Jorhat', 'url': 'https://housing.com/in/buy/real-estate-jorhat'},
    {'name': 'Junagadh', 'url': 'https://housing.com/in/buy/real-estate-junagadh_gujarat'},
    {'name': 'Kabirdham', 'url': 'https://housing.com/in/buy/real-estate-kabirdham'},
    {'name': 'Kadapa', 'url': 'https://housing.com/in/buy/real-estate-kadapa'},
    {'name': 'Kaimur', 'url': 'https://housing.com/in/buy/real-estate-kaimur'},
    {'name': 'Kaithal', 'url': 'https://housing.com/in/buy/real-estate-kaithal'},
    {'name': 'Kakching', 'url': 'https://housing.com/in/buy/real-estate-kakching'},
    {'name': 'Kakinada', 'url': 'https://housing.com/in/buy/real-estate-kakinada'},
    {'name': 'Kalahandi', 'url': 'https://housing.com/in/buy/real-estate-kalahandi'},
    {'name': 'Kalimpong', 'url': 'https://housing.com/in/buy/real-estate-kalimpong'},
    {'name': 'Kallakurichi', 'url': 'https://housing.com/in/buy/real-estate-kallakurichi'},
    {'name': 'Kalol', 'url': 'https://housing.com/in/buy/real-estate-kalol'},
    {'name': 'Kamareddy', 'url': 'https://housing.com/in/buy/real-estate-kamareddy'},
    {'name': 'Kamjong', 'url': 'https://housing.com/in/buy/real-estate-kamjong'},
    {'name': 'Kamrup', 'url': 'https://housing.com/in/buy/real-estate-kamrup'},
    {'name': 'Kanchipuram', 'url': 'https://housing.com/in/buy/real-estate-kanchipuram'},
    {'name': 'Kandhamal', 'url': 'https://housing.com/in/buy/real-estate-kandhamal'},
    {'name': 'Kangpokpi', 'url': 'https://housing.com/in/buy/real-estate-kangpokpi'},
    {'name': 'Kangra', 'url': 'https://housing.com/in/buy/real-estate-kangra'},
    {'name': 'Kanker', 'url': 'https://housing.com/in/buy/real-estate-kanker'},
    {'name': 'Kannauj', 'url': 'https://housing.com/in/buy/real-estate-kannauj'},
    {'name': 'Kannur', 'url': 'https://housing.com/in/buy/real-estate-kannur_kerala'},
    {'name': 'Kanpur', 'url': 'https://housing.com/buy-real-estate-kanpur'},
    {'name': 'Kanyakumari', 'url': 'https://housing.com/in/buy/real-estate-kanyakumari'},
    {'name': 'Kapurthala', 'url': 'https://housing.com/in/buy/real-estate-kapurthala'},
    {'name': 'Karaikudi', 'url': 'https://housing.com/in/buy/real-estate-karaikudi'},
    {'name': 'Karauli', 'url': 'https://housing.com/in/buy/real-estate-karauli'},
    {'name': 'Karbi Anglong', 'url': 'https://housing.com/in/buy/real-estate-karbi_anglong'},
    {'name': 'Kargil', 'url': 'https://housing.com/in/buy/real-estate-kargil'},
    {'name': 'Karimganj', 'url': 'https://housing.com/in/buy/real-estate-karimganj'},
    {'name': 'Karimnagar', 'url': 'https://housing.com/in/buy/real-estate-karimnagar'},
    {'name': 'Karnal', 'url': 'https://housing.com/in/buy/real-estate-karnal_haryana'},
    {'name': 'Karur', 'url': 'https://housing.com/in/buy/real-estate-karur'},
    {'name': 'Karwar', 'url': 'https://housing.com/in/buy/real-estate-karwar'},
    {'name': 'Kasaragod', 'url': 'https://housing.com/in/buy/real-estate-kasaragod'},
    {'name': 'Kasganj', 'url': 'https://housing.com/in/buy/real-estate-kasganj_1'},
    {'name': 'Kashipur', 'url': 'https://housing.com/in/buy/real-estate-kashipur_uttarakhand'},
    {'name': 'Kathua', 'url': 'https://housing.com/in/buy/real-estate-kathua'},
    {'name': 'Katihar', 'url': 'https://housing.com/in/buy/real-estate-katihar'},
    {'name': 'Katni', 'url': 'https://housing.com/in/buy/real-estate-katni'},
    {'name': 'Kaushambi', 'url': 'https://housing.com/in/buy/real-estate-kaushambi'},
    {'name': 'Kendrapara', 'url': 'https://housing.com/in/buy/real-estate-kendrapara'},
    {'name': 'Kendujhar', 'url': 'https://housing.com/in/buy/real-estate-kendujhar'},
    {'name': 'Khagaria', 'url': 'https://housing.com/in/buy/real-estate-khagaria'},
    {'name': 'Khammam', 'url': 'https://housing.com/in/buy/real-estate-khammam'},
    {'name': 'Khandwa', 'url': 'https://housing.com/in/buy/real-estate-khandwa'},
    {'name': 'Kharagpur', 'url': 'https://housing.com/in/buy/real-estate-kharagpur'},
    {'name': 'Khargone', 'url': 'https://housing.com/in/buy/real-estate-khargone'},
    {'name': 'Khawzawl', 'url': 'https://housing.com/in/buy/real-estate-khawzawl'},
    {'name': 'Kheda', 'url': 'https://housing.com/in/buy/real-estate-kheda_1'},
    {'name': 'Khordha District', 'url': 'https://housing.com/in/buy/real-estate-khordha_district'},
    {'name': 'Khowai', 'url': 'https://housing.com/in/buy/real-estate-khowai'},
    {'name': 'Khunti', 'url': 'https://housing.com/in/buy/real-estate-khunti'},
    {'name': 'Kinnaur', 'url': 'https://housing.com/in/buy/real-estate-kinnaur'},
    {'name': 'Kiphire', 'url': 'https://housing.com/in/buy/real-estate-kiphire'},
    {'name': 'Kishanganj', 'url': 'https://housing.com/in/buy/real-estate-kishanganj'},
    {'name': 'Kishtwar', 'url': 'https://housing.com/in/buy/real-estate-kishtwar'},
    {'name': 'Kochi', 'url': 'https://housing.com/in/buy/real-estate-kochi'},
    {'name': 'Kodagu', 'url': 'https://housing.com/in/buy/real-estate-kodagu'},
    {'name': 'Kodaikanal', 'url': 'https://housing.com/in/buy/real-estate-kodaikanal'},
    {'name': 'Koderma', 'url': 'https://housing.com/in/buy/real-estate-koderma'},
    {'name': 'Kohima', 'url': 'https://housing.com/in/buy/real-estate-kohima'},
    {'name': 'Kokrajhar', 'url': 'https://housing.com/in/buy/real-estate-kokrajhar'},
    {'name': 'Kolasib', 'url': 'https://housing.com/in/buy/real-estate-kolasib'},
    {'name': 'Kolhapur', 'url': 'https://housing.com/in/buy/real-estate-kolhapur'},
    {'name': 'Kolkata', 'url': 'https://housing.com/buy-real-estate-kolkata'},
    {'name': 'Kollam', 'url': 'https://housing.com/in/buy/real-estate-kollam'},
    {'name': 'Kondagaon', 'url': 'https://housing.com/in/buy/real-estate-kondagaon'},
    {'name': 'Koppal', 'url': 'https://housing.com/in/buy/real-estate-koppal'},
    {'name': 'Koraput', 'url': 'https://housing.com/in/buy/real-estate-koraput'},
    {'name': 'Korba', 'url': 'https://housing.com/in/buy/real-estate-korba'},
    {'name': 'Koriya', 'url': 'https://housing.com/in/buy/real-estate-koriya'},
    {'name': 'Kota', 'url': 'https://housing.com/in/buy/real-estate-kota_rajasthan'},
    {'name': 'Kothagudem', 'url': 'https://housing.com/in/buy/real-estate-kothagudem'},
    {'name': 'Kottayam', 'url': 'https://housing.com/in/buy/real-estate-kottayam_kerala'},
    {'name': 'Kozhikode', 'url': 'https://housing.com/in/buy/real-estate-kozhikode_kerala'},
    {'name': 'Krishna', 'url': 'https://housing.com/in/buy/real-estate-krishna'},
    {'name': 'Krishnagiri', 'url': 'https://housing.com/in/buy/real-estate-krishnagiri'},
    {'name': 'Kulgam', 'url': 'https://housing.com/in/buy/real-estate-kulgam'},
    {'name': 'Kullu', 'url': 'https://housing.com/in/buy/real-estate-kullu'},
    {'name': 'Kumuram Bheem Asifabad', 'url': 'https://housing.com/in/buy/real-estate-kumuram_bheem_asifabad'},
    {'name': 'Kupwara', 'url': 'https://housing.com/in/buy/real-estate-kupwara'},
    {'name': 'Kurnool', 'url': 'https://housing.com/in/buy/real-estate-kurnool'},
    {'name': 'Kurukshetra', 'url': 'https://housing.com/in/buy/real-estate-kurukshetra_haryana'},
    {'name': 'Kushinagar', 'url': 'https://housing.com/in/buy/real-estate-kushinagar_2'},
    {'name': 'Kutch', 'url': 'https://housing.com/in/buy/real-estate-kutch'},
    {'name': 'Lahaul And Spiti', 'url': 'https://housing.com/in/buy/real-estate-lahaul_and_spiti'},
    {'name': 'Lakhimpur', 'url': 'https://housing.com/in/buy/real-estate-lakhimpur'},
    {'name': 'Lakhimpur Kheri', 'url': 'https://housing.com/in/buy/real-estate-lakhimpur_kheri'},
    {'name': 'Lakhisarai', 'url': 'https://housing.com/in/buy/real-estate-lakhisarai'},
    {'name': 'Lalitpur', 'url': 'https://housing.com/in/buy/real-estate-lalitpur'},
    {'name': 'Latehar', 'url': 'https://housing.com/in/buy/real-estate-latehar'},
    {'name': 'Latur', 'url': 'https://housing.com/in/buy/real-estate-latur'},
    {'name': 'Lawngtlai', 'url': 'https://housing.com/in/buy/real-estate-lawngtlai'},
    {'name': 'Leh', 'url': 'https://housing.com/in/buy/real-estate-leh'},
    {'name': 'Lohardaga', 'url': 'https://housing.com/in/buy/real-estate-lohardaga'},
    {'name': 'Lohit', 'url': 'https://housing.com/in/buy/real-estate-lohit'},
    {'name': 'Lonavala', 'url': 'https://housing.com/in/buy/real-estate-lonavala_1'},
    {'name': 'Longding', 'url': 'https://housing.com/in/buy/real-estate-longding'},
    {'name': 'Longleng', 'url': 'https://housing.com/in/buy/real-estate-longleng'},
    {'name': 'Lower Dibang Valley', 'url': 'https://housing.com/in/buy/real-estate-lower_dibang_valley'},
    {'name': 'Lower Siang', 'url': 'https://housing.com/in/buy/real-estate-lower_siang'},
    {'name': 'Lower Subansiri', 'url': 'https://housing.com/in/buy/real-estate-lower_subansiri'},
    {'name': 'Lucknow', 'url': 'https://housing.com/buy-real-estate-lucknow'},
    {'name': 'Ludhiana', 'url': 'https://housing.com/in/buy/real-estate-ludhiana'},
    {'name': 'Lunglei', 'url': 'https://housing.com/in/buy/real-estate-lunglei'},
    {'name': 'Madanapalle', 'url': 'https://housing.com/in/buy/real-estate-madanapalle'},
    {'name': 'Madhepura', 'url': 'https://housing.com/in/buy/real-estate-madhepura'},
    {'name': 'Madhubani', 'url': 'https://housing.com/in/buy/real-estate-madhubani_bihar'},
    {'name': 'Madurai', 'url': 'https://housing.com/buy-real-estate-madurai_tamil_nadu'},
    {'name': 'Mahabaleshwar', 'url': 'https://housing.com/in/buy/real-estate-mahabaleshwar'},
    {'name': 'Maharajganj', 'url': 'https://housing.com/in/buy/real-estate-maharajganj'},
    {'name': 'Mahasamund', 'url': 'https://housing.com/in/buy/real-estate-mahasamund'},
    {'name': 'Mahendragarh', 'url': 'https://housing.com/in/buy/real-estate-mahendragarh'},
    {'name': 'Mahisagar District', 'url': 'https://housing.com/in/buy/real-estate-mahisagar_district'},
    {'name': 'Mahoba', 'url': 'https://housing.com/in/buy/real-estate-mahoba'},
    {'name': 'Mainpuri', 'url': 'https://housing.com/in/buy/real-estate-mainpuri'},
    {'name': 'Malappuram', 'url': 'https://housing.com/in/buy/real-estate-malappuram'},
    {'name': 'Malda', 'url': 'https://housing.com/in/buy/real-estate-malda'},
    {'name': 'Malegaon', 'url': 'https://housing.com/in/buy/real-estate-malegaon'},
    {'name': 'Malkangiri', 'url': 'https://housing.com/in/buy/real-estate-malkangiri'},
    {'name': 'Mamit', 'url': 'https://housing.com/in/buy/real-estate-mamit'},
    {'name': 'Mancherial', 'url': 'https://housing.com/in/buy/real-estate-mancherial'},
    {'name': 'Mandi', 'url': 'https://housing.com/in/buy/real-estate-mandi'},
    {'name': 'Mandla', 'url': 'https://housing.com/in/buy/real-estate-mandla'},
    {'name': 'Mandsaur', 'url': 'https://housing.com/in/buy/real-estate-mandsaur'},
    {'name': 'Mandya', 'url': 'https://housing.com/in/buy/real-estate-mandya'},
    {'name': 'Mangalore', 'url': 'https://housing.com/in/buy/real-estate-mangaluru'},
    {'name': 'Mansa', 'url': 'https://housing.com/in/buy/real-estate-mansa'},
    {'name': 'Mathura', 'url': 'https://housing.com/in/buy/real-estate-mathura_uttar_pradesh'},
    {'name': 'Mau', 'url': 'https://housing.com/in/buy/real-estate-mau'},
    {'name': 'Mayiladuthurai', 'url': 'https://housing.com/in/buy/real-estate-mayiladuthurai'},
    {'name': 'Mayurbhanj', 'url': 'https://housing.com/in/buy/real-estate-mayurbhanj'},
    {'name': 'Medak', 'url': 'https://housing.com/in/buy/real-estate-medak'},
    {'name': 'Meerut', 'url': 'https://housing.com/in/buy/real-estate-meerut'},
    {'name': 'Mehsana', 'url': 'https://housing.com/in/buy/real-estate-mehsana'},
    {'name': 'Mewat', 'url': 'https://housing.com/in/buy/real-estate-mewat'},
    {'name': 'Middle Andaman', 'url': 'https://housing.com/in/buy/real-estate-middle_andaman'},
    {'name': 'Mirzapur', 'url': 'https://housing.com/in/buy/real-estate-mirzapur'},
    {'name': 'Modasa', 'url': 'https://housing.com/in/buy/real-estate-modasa'},
    {'name': 'Moga', 'url': 'https://housing.com/in/buy/real-estate-moga'},
    {'name': 'Mohali', 'url': 'https://housing.com/in/buy/real-estate-sahibzada_ajit_singh_nagar'},
    {'name': 'Mokokchung', 'url': 'https://housing.com/in/buy/real-estate-mokokchung'},
    {'name': 'Mon', 'url': 'https://housing.com/in/buy/real-estate-mon'},
    {'name': 'Moradabad', 'url': 'https://housing.com/in/buy/real-estate-moradabad'},
    {'name': 'Morbi', 'url': 'https://housing.com/in/buy/real-estate-morbi'},
    {'name': 'Morena', 'url': 'https://housing.com/in/buy/real-estate-morena'},
    {'name': 'Morigaon', 'url': 'https://housing.com/in/buy/real-estate-morigaon'},
    {'name': 'Morinda', 'url': 'https://housing.com/in/buy/real-estate-morinda'},
    {'name': 'Motihari', 'url': 'https://housing.com/in/buy/real-estate-motihari'},
    {'name': 'Mulugu', 'url': 'https://housing.com/in/buy/real-estate-mulugu'},
    {'name': 'Mumbai', 'url': 'https://housing.com/in/buy/real-estate-mumbai'},
    {'name': 'Mungeli', 'url': 'https://housing.com/in/buy/real-estate-mungeli'},
    {'name': 'Munger', 'url': 'https://housing.com/in/buy/real-estate-munger'},
    {'name': 'Murshidabad', 'url': 'https://housing.com/in/buy/real-estate-murshidabad'},
    {'name': 'Mussoorie', 'url': 'https://housing.com/in/buy/real-estate-mussoorie'},
    {'name': 'Muzaffarnagar', 'url': 'https://housing.com/in/buy/real-estate-muzaffarnagar_uttar_pradesh'},
    {'name': 'Muzaffarpur', 'url': 'https://housing.com/in/buy/real-estate-muzaffarpur'},
    {'name': 'Mysore', 'url': 'https://housing.com/buy-real-estate-mysore'},
    {'name': 'Nabarangpur', 'url': 'https://housing.com/in/buy/real-estate-nabarangpur'},
    {'name': 'Nadia', 'url': 'https://housing.com/in/buy/real-estate-nadia'},
    {'name': 'Nadiad', 'url': 'https://housing.com/in/buy/real-estate-nadiad'},
    {'name': 'Nagaon', 'url': 'https://housing.com/in/buy/real-estate-nagaon'},
    {'name': 'Nagapattinam', 'url': 'https://housing.com/in/buy/real-estate-nagapattinam'},
    {'name': 'Nagarkurnool', 'url': 'https://housing.com/in/buy/real-estate-nagarkurnool'},
    {'name': 'Nagaur', 'url': 'https://housing.com/in/buy/real-estate-nagaur'},
    {'name': 'Nagercoil', 'url': 'https://housing.com/in/buy/real-estate-nagercoil'},
    {'name': 'Nagpur', 'url': 'https://housing.com/buy-real-estate-nagpur_maharashtra'},
    {'name': 'Nainital', 'url': 'https://housing.com/in/buy/real-estate-nainital_uttarakhand'},
    {'name': 'Nalanda', 'url': 'https://housing.com/in/buy/real-estate-nalanda'},
    {'name': 'Nalbari', 'url': 'https://housing.com/in/buy/real-estate-nalbari'},
    {'name': 'Nalgonda', 'url': 'https://housing.com/in/buy/real-estate-nalgonda'},
    {'name': 'Namakkal', 'url': 'https://housing.com/in/buy/real-estate-namakkal'},
    {'name': 'Namsai', 'url': 'https://housing.com/in/buy/real-estate-namsai'},
    {'name': 'Nanded', 'url': 'https://housing.com/in/buy/real-estate-nanded'},
    {'name': 'Nandurbar', 'url': 'https://housing.com/in/buy/real-estate-nandurbar'},
    {'name': 'Nandyala', 'url': 'https://housing.com/in/buy/real-estate-nandyala'},
    {'name': 'Narasaraopet', 'url': 'https://housing.com/in/buy/real-estate-narasaraopet'},
    {'name': 'Narayanpet', 'url': 'https://housing.com/in/buy/real-estate-narayanpet'},
    {'name': 'Narayanpur', 'url': 'https://housing.com/in/buy/real-estate-narayanpur'},
    {'name': 'Narmada', 'url': 'https://housing.com/in/buy/real-estate-narmada'},
    {'name': 'Narsinghpur', 'url': 'https://housing.com/in/buy/real-estate-narsinghpur'},
    {'name': 'Nashik', 'url': 'https://housing.com/buy-real-estate-nashik'},
    {'name': 'Nathdwara', 'url': 'https://housing.com/in/buy/real-estate-nathdwara'},
    {'name': 'Navi Mumbai', 'url': 'https://housing.com/in/buy/real-estate-navi_mumbai'},
    {'name': 'Navsari', 'url': 'https://housing.com/in/buy/real-estate-navsari'},
    {'name': 'Nawada', 'url': 'https://housing.com/in/buy/real-estate-nawada'},
    {'name': 'Nawanshahr', 'url': 'https://housing.com/in/buy/real-estate-nawanshahr'},
    {'name': 'Nayagarh', 'url': 'https://housing.com/in/buy/real-estate-nayagarh'},
    {'name': 'Neemrana', 'url': 'https://housing.com/in/buy/real-estate-neemrana'},
    {'name': 'Neemuch', 'url': 'https://housing.com/in/buy/real-estate-neemuch'},
    {'name': 'Nellore', 'url': 'https://housing.com/in/buy/real-estate-nellore_andhra_pradesh'},
    {'name': 'Nicobar', 'url': 'https://housing.com/in/buy/real-estate-nicobar'},
    {'name': 'Nilgiris', 'url': 'https://housing.com/in/buy/real-estate-nilgiris'},
    {'name': 'Nirmal', 'url': 'https://housing.com/in/buy/real-estate-nirmal'},
    {'name': 'Nizamabad', 'url': 'https://housing.com/in/buy/real-estate-nizamabad'},
    {'name': 'Noida', 'url': 'https://housing.com/in/buy/real-estate-noida'},
    {'name': 'Noklak', 'url': 'https://housing.com/in/buy/real-estate-noklak'},
    {'name': 'Noney', 'url': 'https://housing.com/in/buy/real-estate-noney'},
    {'name': 'North 24 Parganas District', 'url': 'https://housing.com/in/buy/real-estate-north_24_parganas_district'},
    {'name': 'North Andaman', 'url': 'https://housing.com/in/buy/real-estate-north_andaman'},
    {'name': 'North Garo Hills', 'url': 'https://housing.com/in/buy/real-estate-north_garo_hills'},
    {'name': 'North Tripura', 'url': 'https://housing.com/in/buy/real-estate-north_tripura'},
    {'name': 'Nuapada', 'url': 'https://housing.com/in/buy/real-estate-nuapada'},
    {'name': 'Ongole', 'url': 'https://housing.com/in/buy/real-estate-ongole'},
    {'name': 'Ooty', 'url': 'https://housing.com/in/buy/real-estate-ooty'},
    {'name': 'Osmanabad', 'url': 'https://housing.com/in/buy/real-estate-osmanabad'},
    {'name': 'Pakur', 'url': 'https://housing.com/in/buy/real-estate-pakur'},
    {'name': 'Palakkad', 'url': 'https://housing.com/in/buy/real-estate-palakkad_kerala'},
    {'name': 'Palamu', 'url': 'https://housing.com/in/buy/real-estate-palamu'},
    {'name': 'Palanpur', 'url': 'https://housing.com/in/buy/real-estate-palanpur'},
    {'name': 'Pali', 'url': 'https://housing.com/in/buy/real-estate-pali'},
    {'name': 'Palwal', 'url': 'https://housing.com/in/buy/real-estate-palwal'},
    {'name': 'Panchkula', 'url': 'https://housing.com/in/buy/real-estate-panchkula_haryana'},
    {'name': 'Panchmahal', 'url': 'https://housing.com/in/buy/real-estate-panchmahal'},
    {'name': 'Panipat', 'url': 'https://housing.com/in/buy/real-estate-panipat_haryana'},
    {'name': 'Panna', 'url': 'https://housing.com/in/buy/real-estate-panna'},
    {'name': 'Papum Pare', 'url': 'https://housing.com/in/buy/real-estate-papum_pare'},
    {'name': 'Parbhani', 'url': 'https://housing.com/in/buy/real-estate-parbhani'},
    {'name': 'Pardi', 'url': 'https://housing.com/in/buy/real-estate-pardi'},
    {'name': 'Pashchim Champaran', 'url': 'https://housing.com/in/buy/real-estate-pashchim_champaran'},
    {'name': 'Patan', 'url': 'https://housing.com/in/buy/real-estate-patan'},
    {'name': 'Pathanamthitta', 'url': 'https://housing.com/in/buy/real-estate-pathanamthitta'},
    {'name': 'Pathankot', 'url': 'https://housing.com/in/buy/real-estate-pathankot'},
    {'name': 'Patiala', 'url': 'https://housing.com/in/buy/real-estate-patiala'},
    {'name': 'Patna', 'url': 'https://housing.com/buy-real-estate-patna'},
    {'name': 'Pauri Garhwal', 'url': 'https://housing.com/in/buy/real-estate-pauri_garhwal'},
    {'name': 'Peddapalli', 'url': 'https://housing.com/in/buy/real-estate-peddapalli'},
    {'name': 'Perambalur', 'url': 'https://housing.com/in/buy/real-estate-perambalur'},
    {'name': 'Peren', 'url': 'https://housing.com/in/buy/real-estate-peren'},
    {'name': 'Phagwara', 'url': 'https://housing.com/in/buy/real-estate-phagwara'},
    {'name': 'Phaltan', 'url': 'https://housing.com/in/buy/real-estate-phaltan_1'},
    {'name': 'Phek', 'url': 'https://housing.com/in/buy/real-estate-phek'},
    {'name': 'Pherzawl', 'url': 'https://housing.com/in/buy/real-estate-pherzawl'},
    {'name': 'Pilibhit', 'url': 'https://housing.com/in/buy/real-estate-pilibhit'},
    {'name': 'Pithoragarh', 'url': 'https://housing.com/in/buy/real-estate-pithoragarh'},
    {'name': 'Pollachi', 'url': 'https://housing.com/in/buy/real-estate-pollachi'},
    {'name': 'Poonch', 'url': 'https://housing.com/in/buy/real-estate-poonch'},
    {'name': 'Porbandar', 'url': 'https://housing.com/in/buy/real-estate-porbandar'},
    {'name': 'Prakasam', 'url': 'https://housing.com/in/buy/real-estate-prakasam'},
    {'name': 'Pratapgarh', 'url': 'https://housing.com/in/buy/real-estate-pratapgarh'},
    {'name': 'Pratapgarh, UP', 'url': 'https://housing.com/in/buy/real-estate-pratapgarh_1'},
    {'name': 'Proddatur', 'url': 'https://housing.com/in/buy/real-estate-proddatur'},
    {'name': 'Puducherry', 'url': 'https://housing.com/in/buy/real-estate-pondicherry'},
    {'name': 'Pudukkottai', 'url': 'https://housing.com/in/buy/real-estate-pudukkottai'},
    {'name': 'Pulwama', 'url': 'https://housing.com/in/buy/real-estate-pulwama'},
    {'name': 'Pune', 'url': 'https://housing.com/in/buy/real-estate-pune'},
    {'name': 'Purba Medinipur', 'url': 'https://housing.com/in/buy/real-estate-purba_medinipur'},
    {'name': 'Puri', 'url': 'https://housing.com/in/buy/real-estate-puri_odisha'},
    {'name': 'Purnea', 'url': 'https://housing.com/in/buy/real-estate-purnea'},
    {'name': 'Purulia', 'url': 'https://housing.com/in/buy/real-estate-purulia'},
    {'name': 'Purvi Champaran', 'url': 'https://housing.com/in/buy/real-estate-purvi_champaran'},
    {'name': 'Raebareli', 'url': 'https://housing.com/in/buy/real-estate-raebareli_1'},
    {'name': 'Raichur', 'url': 'https://housing.com/in/buy/real-estate-raichur'},
    {'name': 'Raigad', 'url': 'https://housing.com/in/buy/real-estate-raigad_1'},
    {'name': 'Raigarh', 'url': 'https://housing.com/in/buy/real-estate-raigarh'},
    {'name': 'Raipur', 'url': 'https://housing.com/in/buy/real-estate-raipur'},
    {'name': 'Raisen', 'url': 'https://housing.com/in/buy/real-estate-raisen_madhya_pradesh'},
    {'name': 'Rajahmundry', 'url': 'https://housing.com/in/buy/real-estate-rajahmundry'},
    {'name': 'Rajanna Sircilla', 'url': 'https://housing.com/in/buy/real-estate-rajanna_sircilla'},
    {'name': 'Rajgarh', 'url': 'https://housing.com/in/buy/real-estate-rajgarh'},
    {'name': 'Rajkot', 'url': 'https://housing.com/in/buy/real-estate-rajkot_gujarat'},
    {'name': 'Rajnandgaon', 'url': 'https://housing.com/in/buy/real-estate-rajnandgaon'},
    {'name': 'Rajouri', 'url': 'https://housing.com/in/buy/real-estate-rajouri'},
    {'name': 'Rajsamand', 'url': 'https://housing.com/in/buy/real-estate-rajsamand'},
    {'name': 'Ramanathapuram', 'url': 'https://housing.com/in/buy/real-estate-ramanathapuram'},
    {'name': 'Ramban', 'url': 'https://housing.com/in/buy/real-estate-ramban'},
    {'name': 'Ramgarh', 'url': 'https://housing.com/in/buy/real-estate-ramgarh_1'},
    {'name': 'Rampur', 'url': 'https://housing.com/in/buy/real-estate-rampur'},
    {'name': 'Ranchi', 'url': 'https://housing.com/buy-real-estate-ranchi'},
    {'name': 'Ranikhet', 'url': 'https://housing.com/in/buy/real-estate-ranikhet'},
    {'name': 'Ranipet', 'url': 'https://housing.com/in/buy/real-estate-ranipet'},
    {'name': 'Ras Al Khaimah', 'url': 'https://housing.com/in/buy/real-estate-ras_al_khaimah'},
    {'name': 'Ratlam', 'url': 'https://housing.com/in/buy/real-estate-ratlam'},
    {'name': 'Ratnagiri', 'url': 'https://housing.com/in/buy/real-estate-ratnagiri_maharashtra'},
    {'name': 'Rayagada', 'url': 'https://housing.com/in/buy/real-estate-rayagada'},
    {'name': 'Reasi', 'url': 'https://housing.com/in/buy/real-estate-reasi'},
    {'name': 'Rewa', 'url': 'https://housing.com/in/buy/real-estate-rewa'},
    {'name': 'Rewari', 'url': 'https://housing.com/in/buy/real-estate-rewari_haryana'},
    {'name': 'Ri Bhoi', 'url': 'https://housing.com/in/buy/real-estate-ri_bhoi'},
    {'name': 'Rishikesh', 'url': 'https://housing.com/in/buy/real-estate-rishikesh'},
    {'name': 'Rohtak', 'url': 'https://housing.com/in/buy/real-estate-rohtak'},
    {'name': 'Rohtas', 'url': 'https://housing.com/in/buy/real-estate-rohtas'},
    {'name': 'Roorkee', 'url': 'https://housing.com/in/buy/real-estate-roorkee'},
    {'name': 'Rourkela', 'url': 'https://housing.com/in/buy/real-estate-rourkela'},
    {'name': 'Rudraprayag', 'url': 'https://housing.com/in/buy/real-estate-rudraprayag'},
    {'name': 'Rudrapur', 'url': 'https://housing.com/in/buy/real-estate-rudrapur_uttarakhand'},
    {'name': 'Rupnagar', 'url': 'https://housing.com/in/buy/real-estate-rupnagar'},
    {'name': 'Ruvak', 'url': 'https://housing.com/in/buy/real-estate-ruvak'},
    {'name': 'Sabarkantha', 'url': 'https://housing.com/in/buy/real-estate-sabarkantha'},
    {'name': 'Sagar', 'url': 'https://housing.com/in/buy/real-estate-sagar'},
    {'name': 'Saharanpur', 'url': 'https://housing.com/in/buy/real-estate-saharanpur_uttar_pradesh'},
    {'name': 'Saharsa', 'url': 'https://housing.com/in/buy/real-estate-saharsa'},
    {'name': 'Sahibganj', 'url': 'https://housing.com/in/buy/real-estate-sahibganj'},
    {'name': 'Salem', 'url': 'https://housing.com/in/buy/real-estate-salem'},
    {'name': 'Samastipur', 'url': 'https://housing.com/in/buy/real-estate-samastipur'},
    {'name': 'Samba', 'url': 'https://housing.com/in/buy/real-estate-samba'},
    {'name': 'Sambalpur', 'url': 'https://housing.com/in/buy/real-estate-sambalpur'},
    {'name': 'Sambhal', 'url': 'https://housing.com/in/buy/real-estate-sambhal'},
    {'name': 'Sangli', 'url': 'https://housing.com/in/buy/real-estate-sangli_maharashtra'},
    {'name': 'Sangrur', 'url': 'https://housing.com/in/buy/real-estate-sangrur'},
    {'name': 'Sant Kabir Nagar', 'url': 'https://housing.com/in/buy/real-estate-sant_kabir_nagar'},
    {'name': 'Saran', 'url': 'https://housing.com/in/buy/real-estate-saran'},
    {'name': 'Sasaram', 'url': 'https://housing.com/in/buy/real-estate-sasaram'},
    {'name': 'Satara', 'url': 'https://housing.com/in/buy/real-estate-satara'},
    {'name': 'Satna', 'url': 'https://housing.com/in/buy/real-estate-satna'},
    {'name': 'Sawaimadhopur', 'url': 'https://housing.com/in/buy/real-estate-sawaimadhopur'},
    {'name': 'Sehore', 'url': 'https://housing.com/in/buy/real-estate-sehore_1'},
    {'name': 'Senapati', 'url': 'https://housing.com/in/buy/real-estate-senapati'},
    {'name': 'Seoni', 'url': 'https://housing.com/in/buy/real-estate-seoni'},
    {'name': 'Seraikela Kharsawan', 'url': 'https://housing.com/in/buy/real-estate-seraikela_kharsawan'},
    {'name': 'Serchhip', 'url': 'https://housing.com/in/buy/real-estate-serchhip'},
    {'name': 'Shahada', 'url': 'https://housing.com/in/buy/real-estate-shahada'},
    {'name': 'Shahdol', 'url': 'https://housing.com/in/buy/real-estate-shahdol'},
    {'name': 'Shahjahanpur', 'url': 'https://housing.com/in/buy/real-estate-shahjahanpur'},
    {'name': 'Shajapur', 'url': 'https://housing.com/in/buy/real-estate-shajapur'},
    {'name': 'Shamli', 'url': 'https://housing.com/in/buy/real-estate-shamli'},
    {'name': 'Sheikhpura', 'url': 'https://housing.com/in/buy/real-estate-sheikhpura'},
    {'name': 'Sheohar', 'url': 'https://housing.com/in/buy/real-estate-sheohar'},
    {'name': 'Sheopur', 'url': 'https://housing.com/in/buy/real-estate-sheopur'},
    {'name': 'Shillong', 'url': 'https://housing.com/in/buy/real-estate-shillong'},
    {'name': 'Shimla', 'url': 'https://housing.com/in/buy/real-estate-shimla_himachal_pradesh'},
    {'name': 'Shivamogga', 'url': 'https://housing.com/in/buy/real-estate-shivamogga'},
    {'name': 'Shivpuri', 'url': 'https://housing.com/in/buy/real-estate-shivpuri'},
    {'name': 'Shopian', 'url': 'https://housing.com/in/buy/real-estate-shopian'},
    {'name': 'Shravasti', 'url': 'https://housing.com/in/buy/real-estate-shravasti'},
    {'name': 'Siaha', 'url': 'https://housing.com/in/buy/real-estate-siaha'},
    {'name': 'Siang', 'url': 'https://housing.com/in/buy/real-estate-siang'},
    {'name': 'Siddharthnagar', 'url': 'https://housing.com/in/buy/real-estate-siddharthnagar'},
    {'name': 'Siddipet', 'url': 'https://housing.com/in/buy/real-estate-siddipet'},
    {'name': 'Sidhi', 'url': 'https://housing.com/in/buy/real-estate-sidhi'},
    {'name': 'Sikar', 'url': 'https://housing.com/in/buy/real-estate-sikar'},
    {'name': 'Silchar', 'url': 'https://housing.com/in/buy/real-estate-silchar'},
    {'name': 'Siliguri', 'url': 'https://housing.com/in/buy/real-estate-siliguri'},
    {'name': 'Silvassa', 'url': 'https://housing.com/in/buy/real-estate-silvassa'},
    {'name': 'Simdega', 'url': 'https://housing.com/in/buy/real-estate-simdega'},
    {'name': 'Sindhudurg', 'url': 'https://housing.com/in/buy/real-estate-sindhudurg'},
    {'name': 'Singapore', 'url': 'https://housing.com/in/buy/real-estate-singapore'},
    {'name': 'Singrauli', 'url': 'https://housing.com/in/buy/real-estate-singrauli'},
    {'name': 'Sipahijala', 'url': 'https://housing.com/in/buy/real-estate-sipahijala'},
    {'name': 'Sirmaur', 'url': 'https://housing.com/in/buy/real-estate-sirmaur'},
    {'name': 'Sirohi', 'url': 'https://housing.com/in/buy/real-estate-sirohi'},
    {'name': 'Sirsa', 'url': 'https://housing.com/in/buy/real-estate-sirsa'},
    {'name': 'Sitamarhi', 'url': 'https://housing.com/in/buy/real-estate-sitamarhi'},
    {'name': 'Sitapur', 'url': 'https://housing.com/in/buy/real-estate-sitapur_2'},
    {'name': 'Sitarganj', 'url': 'https://housing.com/in/buy/real-estate-sitarganj'},
    {'name': 'Sivaganga', 'url': 'https://housing.com/in/buy/real-estate-sivaganga'},
    {'name': 'Sivasagar', 'url': 'https://housing.com/in/buy/real-estate-sivasagar'},
    {'name': 'Siwan', 'url': 'https://housing.com/in/buy/real-estate-siwan'},
    {'name': 'Sojat', 'url': 'https://housing.com/in/buy/real-estate-sojat'},
    {'name': 'Solan', 'url': 'https://housing.com/in/buy/real-estate-solan'},
    {'name': 'Solapur', 'url': 'https://housing.com/in/buy/real-estate-solapur_maharashtra'},
    {'name': 'Sonbhadra', 'url': 'https://housing.com/in/buy/real-estate-sonbhadra'},
    {'name': 'Sonipat', 'url': 'https://housing.com/in/buy/real-estate-sonepat'},
    {'name': 'Sonitpur', 'url': 'https://housing.com/in/buy/real-estate-sonitpur'},
    {'name': 'South 24 Parganas', 'url': 'https://housing.com/in/buy/real-estate-south_24_parganas'},
    {'name': 'South Andaman', 'url': 'https://housing.com/in/buy/real-estate-south_andaman'},
    {'name': 'South Garo Hills', 'url': 'https://housing.com/in/buy/real-estate-south_garo_hills'},
    {'name': 'South Tripura', 'url': 'https://housing.com/in/buy/real-estate-south_tripura_1'},
    {'name': 'South West Khasi Hills', 'url': 'https://housing.com/in/buy/real-estate-south_west_khasi_hills'},
    {'name': 'Sri Ganganagar', 'url': 'https://housing.com/in/buy/real-estate-sri_ganganagar_rajasthan'},
    {'name': 'Sri Muktsar Sahib', 'url': 'https://housing.com/in/buy/real-estate-sri_muktsar_sahib'},
    {'name': 'Srikakulam', 'url': 'https://housing.com/in/buy/real-estate-srikakulam'},
    {'name': 'Srinagar', 'url': 'https://housing.com/in/buy/real-estate-srinagar'},
    {'name': 'Subarnapur', 'url': 'https://housing.com/in/buy/real-estate-subarnapur'},
    {'name': 'Sukma', 'url': 'https://housing.com/in/buy/real-estate-sukma'},
    {'name': 'Sultanpur', 'url': 'https://housing.com/in/buy/real-estate-sultanpur'},
    {'name': 'Sundargarh', 'url': 'https://housing.com/in/buy/real-estate-sundargarh'},
    {'name': 'Supaul', 'url': 'https://housing.com/in/buy/real-estate-supaul'},
    {'name': 'Surajpur', 'url': 'https://housing.com/in/buy/real-estate-surajpur'},
    {'name': 'Surat', 'url': 'https://housing.com/buy-real-estate-surat'},
    {'name': 'Surendranagar', 'url': 'https://housing.com/in/buy/real-estate-surendranagar_gujarat'},
    {'name': 'Surguja', 'url': 'https://housing.com/in/buy/real-estate-surguja_1'},
    {'name': 'Suryapet', 'url': 'https://housing.com/in/buy/real-estate-suryapet'},
    {'name': 'Tadepalligudem', 'url': 'https://housing.com/in/buy/real-estate-tadepalligudem'},
    {'name': 'Tamenglong', 'url': 'https://housing.com/in/buy/real-estate-tamenglong'},
    {'name': 'Tapi', 'url': 'https://housing.com/in/buy/real-estate-tapi'},
    {'name': 'Tarn Taran Sahib', 'url': 'https://housing.com/in/buy/real-estate-tarn_taran_sahib'},
    {'name': 'Tawang', 'url': 'https://housing.com/in/buy/real-estate-tawang'},
    {'name': 'Tehri', 'url': 'https://housing.com/in/buy/real-estate-tehri_garhwal_district'},
    {'name': 'Tenali', 'url': 'https://housing.com/in/buy/real-estate-tenali'},
    {'name': 'Tengnoupal', 'url': 'https://housing.com/in/buy/real-estate-tengnoupal'},
    {'name': 'Tezpur', 'url': 'https://housing.com/in/buy/real-estate-tezpur'},
    {'name': 'Thane', 'url': 'https://housing.com/in/buy/real-estate-thane'},
    {'name': 'Thanjavur', 'url': 'https://housing.com/in/buy/real-estate-thanjavur'},
    {'name': 'Theni', 'url': 'https://housing.com/in/buy/real-estate-theni_tamil_nadu'},
    {'name': 'Thiruvananthapuram', 'url': 'https://housing.com/in/buy/real-estate-thiruvananthapuram'},
    {'name': 'Thoothukudi', 'url': 'https://housing.com/in/buy/real-estate-thoothukudi'},
    {'name': 'Thoubal', 'url': 'https://housing.com/in/buy/real-estate-thoubal'},
    {'name': 'Thrissur', 'url': 'https://housing.com/in/buy/real-estate-thrissur_kerala'},
    {'name': 'Tikamgarh', 'url': 'https://housing.com/in/buy/real-estate-tikamgarh'},
    {'name': 'Tinsukia', 'url': 'https://housing.com/in/buy/real-estate-tinsukia'},
    {'name': 'Tiruchengode', 'url': 'https://housing.com/in/buy/real-estate-tiruchengode'},
    {'name': 'Tiruchirappalli', 'url': 'https://housing.com/in/buy/real-estate-tiruchirappalli'},
    {'name': 'Tirunelveli', 'url': 'https://housing.com/in/buy/real-estate-tirunelveli'},
    {'name': 'Tirupathi', 'url': 'https://housing.com/in/buy/real-estate-tirupati'},
    {'name': 'Tirupathur', 'url': 'https://housing.com/in/buy/real-estate-tirupattur'},
    {'name': 'Tiruppur', 'url': 'https://housing.com/in/buy/real-estate-tiruppur_tamil_nadu'},
    {'name': 'Tiruvannamalai', 'url': 'https://housing.com/in/buy/real-estate-tiruvannamalai'},
    {'name': 'Tiruvarur', 'url': 'https://housing.com/in/buy/real-estate-tiruvarur'},
    {'name': 'Tonk', 'url': 'https://housing.com/in/buy/real-estate-tonk'},
    {'name': 'Tuensang', 'url': 'https://housing.com/in/buy/real-estate-tuensang'},
    {'name': 'Tumkur', 'url': 'https://housing.com/in/buy/real-estate-tumakuru'},
    {'name': 'Udaipur', 'url': 'https://housing.com/in/buy/real-estate-udaipur_rajasthan'},
    {'name': 'Udalguri', 'url': 'https://housing.com/in/buy/real-estate-udalguri'},
    {'name': 'Udham Singh Nagar', 'url': 'https://housing.com/in/buy/real-estate-udham_singh_nagar'},
    {'name': 'Udhampur', 'url': 'https://housing.com/in/buy/real-estate-udhampur'},
    {'name': 'Udupi', 'url': 'https://housing.com/in/buy/real-estate-udupi_karnataka'},
    {'name': 'Ujjain', 'url': 'https://housing.com/in/buy/real-estate-ujjain'},
    {'name': 'Ukhrul', 'url': 'https://housing.com/in/buy/real-estate-ukhrul'},
    {'name': 'Umargam', 'url': 'https://housing.com/in/buy/real-estate-umargam'},
    {'name': 'Umaria', 'url': 'https://housing.com/in/buy/real-estate-umaria'},
    {'name': 'Una', 'url': 'https://housing.com/in/buy/real-estate-una'},
    {'name': 'Unakoti', 'url': 'https://housing.com/in/buy/real-estate-unakoti'},
    {'name': 'Unnao', 'url': 'https://housing.com/in/buy/real-estate-unnao'},
    {'name': 'Upper Siang', 'url': 'https://housing.com/in/buy/real-estate-upper_siang_1'},
    {'name': 'Upper Subansiri', 'url': 'https://housing.com/in/buy/real-estate-upper_subansiri'},
    {'name': 'Uttar Dinajpur', 'url': 'https://housing.com/in/buy/real-estate-uttar_dinajpur'},
    {'name': 'Uttara Kannada', 'url': 'https://housing.com/in/buy/real-estate-uttara_kannada'},
    {'name': 'Uttarkashi District', 'url': 'https://housing.com/in/buy/real-estate-uttarkashi_1'},
    {'name': 'Vadodara', 'url': 'https://housing.com/buy-real-estate-vadodara'},
    {'name': 'Vaishali', 'url': 'https://housing.com/in/buy/real-estate-vaishali'},
    {'name': 'Valsad', 'url': 'https://housing.com/in/buy/real-estate-valsad'},
    {'name': 'Vapi', 'url': 'https://housing.com/in/buy/real-estate-vapi'},
    {'name': 'Varanasi', 'url': 'https://housing.com/buy-real-estate-varanasi_uttar_pradesh'},
    {'name': 'Vellore', 'url': 'https://housing.com/in/buy/real-estate-vellore'},
    {'name': 'Vidisha', 'url': 'https://housing.com/in/buy/real-estate-vidisha'},
    {'name': 'Vijayapura', 'url': 'https://housing.com/in/buy/real-estate-vijayapura'},
    {'name': 'Vijayawada', 'url': 'https://housing.com/in/buy/real-estate-vijayawada'},
    {'name': 'Vikarabad', 'url': 'https://housing.com/in/buy/real-estate-vikarabad'},
    {'name': 'Viluppuram', 'url': 'https://housing.com/in/buy/real-estate-viluppuram'},
    {'name': 'Virudhunagar', 'url': 'https://housing.com/in/buy/real-estate-virudhunagar'},
    {'name': 'Visakhapatnam', 'url': 'https://housing.com/buy-real-estate-visakhapatnam'},
    {'name': 'Visnagar', 'url': 'https://housing.com/in/buy/real-estate-visnagar_1'},
    {'name': 'Vizianagaram', 'url': 'https://housing.com/in/buy/real-estate-vizianagaram'},
    {'name': 'Vrindavan', 'url': 'https://housing.com/in/buy/real-estate-vrindavan_1'},
    {'name': 'Wanaparthy', 'url': 'https://housing.com/in/buy/real-estate-wanaparthy'},
    {'name': 'Warangal', 'url': 'https://housing.com/in/buy/real-estate-warangal'},
    {'name': 'Wardha', 'url': 'https://housing.com/in/buy/real-estate-wardha'},
    {'name': 'Washim', 'url': 'https://housing.com/in/buy/real-estate-washim'},
    {'name': 'Wayanad', 'url': 'https://housing.com/in/buy/real-estate-wayanad'},
    {'name': 'West Garo Hills', 'url': 'https://housing.com/in/buy/real-estate-west_garo_hills'},
    {'name': 'West Godavari', 'url': 'https://housing.com/in/buy/real-estate-west_godavari'},
    {'name': 'West Jaintia Hills', 'url': 'https://housing.com/in/buy/real-estate-west_jaintia_hills'},
    {'name': 'West Kameng', 'url': 'https://housing.com/in/buy/real-estate-west_kameng'},
    {'name': 'West Karbi Anglong', 'url': 'https://housing.com/in/buy/real-estate-west_karbi_anglong'},
    {'name': 'West Khasi Hills', 'url': 'https://housing.com/in/buy/real-estate-west_khasi_hills'},
    {'name': 'West Medinipur', 'url': 'https://housing.com/in/buy/real-estate-west_medinipur'},
    {'name': 'West Siang', 'url': 'https://housing.com/in/buy/real-estate-west_siang_1'},
    {'name': 'West Singhbhum', 'url': 'https://housing.com/in/buy/real-estate-west_singhbhum'},
    {'name': 'West Tripura', 'url': 'https://housing.com/in/buy/real-estate-west_tripura'},
    {'name': 'Wokha', 'url': 'https://housing.com/in/buy/real-estate-wokha'},
    {'name': 'Yadgir', 'url': 'https://housing.com/in/buy/real-estate-yadgir'},
    {'name': 'Yamuna Nagar', 'url': 'https://housing.com/in/buy/real-estate-yamuna_nagar_haryana'},
    {'name': 'Yavatmal', 'url': 'https://housing.com/in/buy/real-estate-yavatmal'},
    {'name': 'Zirakpur', 'url': 'https://housing.com/in/buy/real-estate-zirakpur'},
    {'name': 'Zunheboto', 'url': 'https://housing.com/in/buy/real-estate-zunheboto'},
  ];
}
